// GERADO por scripts (a partir de LwjglGlfwKeycode.java do PojavLauncher). Não editar à mão.
export interface KeyInfo { glfw: number; name: string; key: string; code: string; keyCode: number; label: string }
export const KEYS: KeyInfo[] = [
	{ glfw: 32, name: 'SPACE', key: ' ', code: 'Space', keyCode: 32, label: 'Espaço' },
	{ glfw: 39, name: 'APOSTROPHE', key: '\'', code: 'Quote', keyCode: 222, label: '\'' },
	{ glfw: 44, name: 'COMMA', key: ',', code: 'Comma', keyCode: 188, label: ',' },
	{ glfw: 45, name: 'MINUS', key: '-', code: 'Minus', keyCode: 189, label: '-' },
	{ glfw: 46, name: 'PERIOD', key: '.', code: 'Period', keyCode: 190, label: '.' },
	{ glfw: 47, name: 'SLASH', key: '/', code: 'Slash', keyCode: 191, label: '/' },
	{ glfw: 48, name: '0', key: '0', code: 'Digit0', keyCode: 48, label: '0' },
	{ glfw: 49, name: '1', key: '1', code: 'Digit1', keyCode: 49, label: '1' },
	{ glfw: 50, name: '2', key: '2', code: 'Digit2', keyCode: 50, label: '2' },
	{ glfw: 51, name: '3', key: '3', code: 'Digit3', keyCode: 51, label: '3' },
	{ glfw: 52, name: '4', key: '4', code: 'Digit4', keyCode: 52, label: '4' },
	{ glfw: 53, name: '5', key: '5', code: 'Digit5', keyCode: 53, label: '5' },
	{ glfw: 54, name: '6', key: '6', code: 'Digit6', keyCode: 54, label: '6' },
	{ glfw: 55, name: '7', key: '7', code: 'Digit7', keyCode: 55, label: '7' },
	{ glfw: 56, name: '8', key: '8', code: 'Digit8', keyCode: 56, label: '8' },
	{ glfw: 57, name: '9', key: '9', code: 'Digit9', keyCode: 57, label: '9' },
	{ glfw: 59, name: 'SEMICOLON', key: ';', code: 'Semicolon', keyCode: 186, label: ';' },
	{ glfw: 61, name: 'EQUAL', key: '=', code: 'Equal', keyCode: 187, label: '=' },
	{ glfw: 65, name: 'A', key: 'a', code: 'KeyA', keyCode: 65, label: 'A' },
	{ glfw: 66, name: 'B', key: 'b', code: 'KeyB', keyCode: 66, label: 'B' },
	{ glfw: 67, name: 'C', key: 'c', code: 'KeyC', keyCode: 67, label: 'C' },
	{ glfw: 68, name: 'D', key: 'd', code: 'KeyD', keyCode: 68, label: 'D' },
	{ glfw: 69, name: 'E', key: 'e', code: 'KeyE', keyCode: 69, label: 'E' },
	{ glfw: 70, name: 'F', key: 'f', code: 'KeyF', keyCode: 70, label: 'F' },
	{ glfw: 71, name: 'G', key: 'g', code: 'KeyG', keyCode: 71, label: 'G' },
	{ glfw: 72, name: 'H', key: 'h', code: 'KeyH', keyCode: 72, label: 'H' },
	{ glfw: 73, name: 'I', key: 'i', code: 'KeyI', keyCode: 73, label: 'I' },
	{ glfw: 74, name: 'J', key: 'j', code: 'KeyJ', keyCode: 74, label: 'J' },
	{ glfw: 75, name: 'K', key: 'k', code: 'KeyK', keyCode: 75, label: 'K' },
	{ glfw: 76, name: 'L', key: 'l', code: 'KeyL', keyCode: 76, label: 'L' },
	{ glfw: 77, name: 'M', key: 'm', code: 'KeyM', keyCode: 77, label: 'M' },
	{ glfw: 78, name: 'N', key: 'n', code: 'KeyN', keyCode: 78, label: 'N' },
	{ glfw: 79, name: 'O', key: 'o', code: 'KeyO', keyCode: 79, label: 'O' },
	{ glfw: 80, name: 'P', key: 'p', code: 'KeyP', keyCode: 80, label: 'P' },
	{ glfw: 81, name: 'Q', key: 'q', code: 'KeyQ', keyCode: 81, label: 'Q' },
	{ glfw: 82, name: 'R', key: 'r', code: 'KeyR', keyCode: 82, label: 'R' },
	{ glfw: 83, name: 'S', key: 's', code: 'KeyS', keyCode: 83, label: 'S' },
	{ glfw: 84, name: 'T', key: 't', code: 'KeyT', keyCode: 84, label: 'T' },
	{ glfw: 85, name: 'U', key: 'u', code: 'KeyU', keyCode: 85, label: 'U' },
	{ glfw: 86, name: 'V', key: 'v', code: 'KeyV', keyCode: 86, label: 'V' },
	{ glfw: 87, name: 'W', key: 'w', code: 'KeyW', keyCode: 87, label: 'W' },
	{ glfw: 88, name: 'X', key: 'x', code: 'KeyX', keyCode: 88, label: 'X' },
	{ glfw: 89, name: 'Y', key: 'y', code: 'KeyY', keyCode: 89, label: 'Y' },
	{ glfw: 90, name: 'Z', key: 'z', code: 'KeyZ', keyCode: 90, label: 'Z' },
	{ glfw: 91, name: 'LEFT_BRACKET', key: '[', code: 'BracketLeft', keyCode: 219, label: '[' },
	{ glfw: 92, name: 'BACKSLASH', key: '\\', code: 'Backslash', keyCode: 220, label: '\\' },
	{ glfw: 93, name: 'RIGHT_BRACKET', key: ']', code: 'BracketRight', keyCode: 221, label: ']' },
	{ glfw: 96, name: 'GRAVE_ACCENT', key: '`', code: 'Backquote', keyCode: 192, label: '`' },
	{ glfw: 161, name: 'WORLD_1', key: '<', code: 'IntlBackslash', keyCode: 226, label: 'World 1' },
	{ glfw: 162, name: 'WORLD_2', key: '>', code: 'IntlBackslash', keyCode: 226, label: 'World 2' },
	{ glfw: 256, name: 'ESCAPE', key: 'Escape', code: 'Escape', keyCode: 27, label: 'Esc' },
	{ glfw: 257, name: 'ENTER', key: 'Enter', code: 'Enter', keyCode: 13, label: 'Enter' },
	{ glfw: 258, name: 'TAB', key: 'Tab', code: 'Tab', keyCode: 9, label: 'Tab' },
	{ glfw: 259, name: 'BACKSPACE', key: 'Backspace', code: 'Backspace', keyCode: 8, label: 'Backspace' },
	{ glfw: 260, name: 'INSERT', key: 'Insert', code: 'Insert', keyCode: 45, label: 'Insert' },
	{ glfw: 261, name: 'DELETE', key: 'Delete', code: 'Delete', keyCode: 46, label: 'Delete' },
	{ glfw: 262, name: 'RIGHT', key: 'ArrowRight', code: 'ArrowRight', keyCode: 39, label: 'Seta →' },
	{ glfw: 263, name: 'LEFT', key: 'ArrowLeft', code: 'ArrowLeft', keyCode: 37, label: 'Seta ←' },
	{ glfw: 264, name: 'DOWN', key: 'ArrowDown', code: 'ArrowDown', keyCode: 40, label: 'Seta ↓' },
	{ glfw: 265, name: 'UP', key: 'ArrowUp', code: 'ArrowUp', keyCode: 38, label: 'Seta ↑' },
	{ glfw: 266, name: 'PAGE_UP', key: 'PageUp', code: 'PageUp', keyCode: 33, label: 'Page Up' },
	{ glfw: 267, name: 'PAGE_DOWN', key: 'PageDown', code: 'PageDown', keyCode: 34, label: 'Page Down' },
	{ glfw: 268, name: 'HOME', key: 'Home', code: 'Home', keyCode: 36, label: 'Home' },
	{ glfw: 269, name: 'END', key: 'End', code: 'End', keyCode: 35, label: 'End' },
	{ glfw: 280, name: 'CAPS_LOCK', key: 'CapsLock', code: 'CapsLock', keyCode: 20, label: 'Caps Lock' },
	{ glfw: 281, name: 'SCROLL_LOCK', key: 'ScrollLock', code: 'ScrollLock', keyCode: 145, label: 'Scroll Lock' },
	{ glfw: 282, name: 'NUM_LOCK', key: 'NumLock', code: 'NumLock', keyCode: 144, label: 'Num Lock' },
	{ glfw: 283, name: 'PRINT_SCREEN', key: 'PrintScreen', code: 'PrintScreen', keyCode: 44, label: 'Print Screen' },
	{ glfw: 284, name: 'PAUSE', key: 'Pause', code: 'Pause', keyCode: 19, label: 'Pause' },
	{ glfw: 290, name: 'F1', key: 'F1', code: 'F1', keyCode: 112, label: 'F1' },
	{ glfw: 291, name: 'F2', key: 'F2', code: 'F2', keyCode: 113, label: 'F2' },
	{ glfw: 292, name: 'F3', key: 'F3', code: 'F3', keyCode: 114, label: 'F3' },
	{ glfw: 293, name: 'F4', key: 'F4', code: 'F4', keyCode: 115, label: 'F4' },
	{ glfw: 294, name: 'F5', key: 'F5', code: 'F5', keyCode: 116, label: 'F5' },
	{ glfw: 295, name: 'F6', key: 'F6', code: 'F6', keyCode: 117, label: 'F6' },
	{ glfw: 296, name: 'F7', key: 'F7', code: 'F7', keyCode: 118, label: 'F7' },
	{ glfw: 297, name: 'F8', key: 'F8', code: 'F8', keyCode: 119, label: 'F8' },
	{ glfw: 298, name: 'F9', key: 'F9', code: 'F9', keyCode: 120, label: 'F9' },
	{ glfw: 299, name: 'F10', key: 'F10', code: 'F10', keyCode: 121, label: 'F10' },
	{ glfw: 300, name: 'F11', key: 'F11', code: 'F11', keyCode: 122, label: 'F11' },
	{ glfw: 301, name: 'F12', key: 'F12', code: 'F12', keyCode: 123, label: 'F12' },
	{ glfw: 302, name: 'F13', key: 'F13', code: 'F13', keyCode: 124, label: 'F13' },
	{ glfw: 303, name: 'F14', key: 'F14', code: 'F14', keyCode: 125, label: 'F14' },
	{ glfw: 304, name: 'F15', key: 'F15', code: 'F15', keyCode: 126, label: 'F15' },
	{ glfw: 305, name: 'F16', key: 'F16', code: 'F16', keyCode: 127, label: 'F16' },
	{ glfw: 306, name: 'F17', key: 'F17', code: 'F17', keyCode: 128, label: 'F17' },
	{ glfw: 307, name: 'F18', key: 'F18', code: 'F18', keyCode: 129, label: 'F18' },
	{ glfw: 308, name: 'F19', key: 'F19', code: 'F19', keyCode: 130, label: 'F19' },
	{ glfw: 309, name: 'F20', key: 'F20', code: 'F20', keyCode: 131, label: 'F20' },
	{ glfw: 310, name: 'F21', key: 'F21', code: 'F21', keyCode: 132, label: 'F21' },
	{ glfw: 311, name: 'F22', key: 'F22', code: 'F22', keyCode: 133, label: 'F22' },
	{ glfw: 312, name: 'F23', key: 'F23', code: 'F23', keyCode: 134, label: 'F23' },
	{ glfw: 313, name: 'F24', key: 'F24', code: 'F24', keyCode: 135, label: 'F24' },
	{ glfw: 314, name: 'F25', key: 'F25', code: 'F25', keyCode: 0, label: 'F25' },
	{ glfw: 320, name: 'KP_0', key: '0', code: 'Numpad0', keyCode: 96, label: 'Num 0' },
	{ glfw: 321, name: 'KP_1', key: '1', code: 'Numpad1', keyCode: 97, label: 'Num 1' },
	{ glfw: 322, name: 'KP_2', key: '2', code: 'Numpad2', keyCode: 98, label: 'Num 2' },
	{ glfw: 323, name: 'KP_3', key: '3', code: 'Numpad3', keyCode: 99, label: 'Num 3' },
	{ glfw: 324, name: 'KP_4', key: '4', code: 'Numpad4', keyCode: 100, label: 'Num 4' },
	{ glfw: 325, name: 'KP_5', key: '5', code: 'Numpad5', keyCode: 101, label: 'Num 5' },
	{ glfw: 326, name: 'KP_6', key: '6', code: 'Numpad6', keyCode: 102, label: 'Num 6' },
	{ glfw: 327, name: 'KP_7', key: '7', code: 'Numpad7', keyCode: 103, label: 'Num 7' },
	{ glfw: 328, name: 'KP_8', key: '8', code: 'Numpad8', keyCode: 104, label: 'Num 8' },
	{ glfw: 329, name: 'KP_9', key: '9', code: 'Numpad9', keyCode: 105, label: 'Num 9' },
	{ glfw: 330, name: 'KP_DECIMAL', key: '.', code: 'NumpadDecimal', keyCode: 110, label: 'Num .' },
	{ glfw: 331, name: 'KP_DIVIDE', key: '/', code: 'NumpadDivide', keyCode: 111, label: 'Num /' },
	{ glfw: 332, name: 'KP_MULTIPLY', key: '*', code: 'NumpadMultiply', keyCode: 106, label: 'Num *' },
	{ glfw: 333, name: 'KP_SUBTRACT', key: '-', code: 'NumpadSubtract', keyCode: 109, label: 'Num -' },
	{ glfw: 334, name: 'KP_ADD', key: '+', code: 'NumpadAdd', keyCode: 107, label: 'Num +' },
	{ glfw: 335, name: 'KP_ENTER', key: 'Enter', code: 'NumpadEnter', keyCode: 13, label: 'Num Enter' },
	{ glfw: 336, name: 'KP_EQUAL', key: '=', code: 'NumpadEqual', keyCode: 187, label: 'Num =' },
	{ glfw: 340, name: 'LEFT_SHIFT', key: 'Shift', code: 'ShiftLeft', keyCode: 16, label: 'Shift (esq.)' },
	{ glfw: 341, name: 'LEFT_CONTROL', key: 'Control', code: 'ControlLeft', keyCode: 17, label: 'Ctrl (esq.)' },
	{ glfw: 342, name: 'LEFT_ALT', key: 'Alt', code: 'AltLeft', keyCode: 18, label: 'Alt (esq.)' },
	{ glfw: 343, name: 'LEFT_SUPER', key: 'Meta', code: 'MetaLeft', keyCode: 91, label: 'Meta (esq.)' },
	{ glfw: 344, name: 'RIGHT_SHIFT', key: 'Shift', code: 'ShiftRight', keyCode: 16, label: 'Shift (dir.)' },
	{ glfw: 345, name: 'RIGHT_CONTROL', key: 'Control', code: 'ControlRight', keyCode: 17, label: 'Ctrl (dir.)' },
	{ glfw: 346, name: 'RIGHT_ALT', key: 'Alt', code: 'AltRight', keyCode: 18, label: 'Alt (dir.)' },
	{ glfw: 347, name: 'RIGHT_SUPER', key: 'Meta', code: 'MetaRight', keyCode: 92, label: 'Meta (dir.)' },
	{ glfw: 348, name: 'MENU', key: 'ContextMenu', code: 'ContextMenu', keyCode: 93, label: 'Menu' },
];
export const KEY_BY_GLFW: Record<number, KeyInfo> = Object.fromEntries(KEYS.map(k => [k.glfw, k]));
